# Generated by Django 4.2.4 on 2023-08-10 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=100)),
                ('industry_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='total_investment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='client_industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.clientindustry'),
        ),
    ]
