# Generated by Django 4.2.4 on 2023-08-11 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_clientindustry_clientportfolio_total_investment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientportfolio',
            name='client_industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientindustry'),
        ),
    ]
