# Generated by Django 4.2.4 on 2023-08-16 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_organization_rename_is_active_clientportfolio_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 16, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
